---
- hosts: apt
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu | Debian"

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu | Debian"

  - name: install support for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu | Debian"

  - name: add php support for apache
    ansible.builtin.dnf:
      name: php
      state: latest
    when: ansible_distribution == "Fefora"
