---
- hosts: all
  become: true
  pre_tasks:
  - name: install updates for fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"
      
  - name: install updates for ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install apache on web servers
    tags: apache,ubuntu
    ansible.builtin.package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu" and ansible_distribution == "Debian"

  - name: install apache on web servers (fedora)
    tags: apache,fedora
    ansible.builtin.dnf:
      name: httpd
    when: ansible_distribution == "Fedora"

  - name: ensure apache is running (ubuntu / debian)
    tags: apache,ubuntu
    ansible.builtin.service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu" and ansible_distribution == "Debian"

  - name: ensure apache is running (fedora)
    tags: apache,fedora
    ansible.builtin.service:
      name: httpd
      state: started
    when: ansible_distribution == "Fedora"

  - name: change email addres for apache admin
    tags: apache,fedora
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin fedora2@somewhere.net
    when: ansible_distribution == "Fedora"
    register: httpdadminemail

  - name: restart httpd (fedora)
    tags: apache,fedora
    ansible.builtin.service:
      name: httpd
      state: restarted
    when: httpdadminemail.changed 

  - name: copy html file for site
    tags: apache,ubuntu
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  tags: db,fedora
  become: true
  tasks:
  - name: install mysql 
    ansible.builtin.package:
      name:
        - "{{ mysql_package }}"
      state: latest
